### ISSUE TITLE
v0.7.0 - Pre-release checklist

### ISSUE THREAD

**Issue by graza-io** [theapsgroup/steampipe-plugin-gitlab#74]
- [x] Verify Statistics in `gitlab_project` table.
- [x] Verify `ref` column on `gitlab_project_repository`
- [ ] Upgrade Steampipe SDK Version
- [ ] Upgrade GitLab SDK Version
  - [ ] `Group` struct has `EmailsDisabled`=>`EmailsEnabled` & `SharedRunnersEnabled` replaced by a new struct `SharedRunnersSetting`
  - [ ] Verify Changes on underlying `MergeRequest` struct do not break tables.
  - [ ] Verify removal of `Public` (bool) field on `Project` struct does not break tables.
  - [ ] `AuditEvent` now have `EventType` property
  - [ ] `Commit` now has `Author` property
  - [ ] `ContainerRegistry` now has `Status` property
  - [ ] `GroupMember` now has `MemberRole` property
